### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by BarryZM** [sahilnare/beta07_Pied_Piper#1]

**Comment by sahilnare** [comment]
To run the nodejs app (main dashboard website):
  cd Project_Directory
  yarn install
  yarn build
  yarn start
The app will run on http://localhost:8000/

To run the disease prediction flask app and covid prediction python program:
  cd flask_app_covid_from_cough
  python app.py
Then go to the url given in the command line
For disease prediction go to url/predict
For covid prediction go to url/audio

**Comment by BarryZM** [comment]
Thank you very much
